---
title: A sudo command for Cygwin
date: 2021-02-24
draft: false

showToc: false
TocOpen: false
hidemeta: false
disableShare: false
comments: false

series:
- Things I learned

categories:
- IT Operations

topics:
- Cygwin

tags:
- Command-line Interfaces (CLI)
- Cygwin
- Linux / Unix
- Sudo
- Windows
- ZSH / Bash
---

:source-language: console

:url_cygwin: https://cygwin.com
:url_sudo: https://www.sudo.ws
:url_zsh: https://www.zsh.org


You can run commands from {url_cygwin}[Cygwin] with elevated permissions.

On Windows, you have something like `Run as different user` or `Run as administrator`.
And on Linux, you probably use {url_sudo}[`sudo`] for this.

To get similar functionality on Cygwin, you can add a new alias to your shell's config file.
The following is for {url_zsh}[ZSH], but it should also work with other bash-like shells.

.`~/.zshrc`
----
alias sudo='cygstart --action=runas'
----

Now you can run something like this to test the alias.

----
$ sudo touch sudo-test
----

Windows will ask for your username and password.
Then it will run the command in the context of the given user.

That works, but it is a bit of a hack.
The command is executed in a new Cygwin process, which is closed when the command returns.
Also, the password/user prompt is uncomfortable at best compared to the real `sudo` user experience.
