enableRobotsTXT: true

imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart

outputs:
  home:
    - HTML
    - RSS
    - JSON

minify:
  disableXML: true

markup:
  asciidocExt:
    attributes:
      figure-caption!:
      showtitle: true

ignoreFiles:
  - database-fundamentals


###############################################################################
# Site settings
###############################################################################

baseURL: "https://www.andreaslongo.com"
theme: papermod
defaultContentLanguage: en

params:
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowFullTextinRSS: true
  ShowPostNavLinks: true
  ShowReadingTime: false
  ShowShareButtons: true
  author: Andreas Longo
  comments: false
  defaultTheme: auto
  disableThemeToggle: false
  displayFullLangName: true

  cover:
    linkFullImages: false
    responsiveImages: true

  assets:
    disableFingerprinting: false

  socialIcons:
    - name: linkedin
      url: https://www.linkedin.com/in/andreaslongo
    - name: twitter
      url: https://twitter.com/andreas_longo
    - name: github
      url: https://github.com/andreaslongo
    - name: gitlab
      url: https://gitlab.com/andreaslongo

languages:
  en:
    languageName: English
    languageCode: en-us
    weight: 1
    title: Andreas Longo
    description: Personal website

    menu:
      main:
        - name: Blog
          url: blog
        - name: Contact
          url: contact
        - name: Search
          url: search
        - name: Training
          url: training

    profileMode:
      enabled: true
      title: Senior IT Systems Engineer
      subtitle: IT Consultant
      imageUrl: /images/brainstorming-over-paper-5fNmWej4tAA.min.jpg
      imageWidth: 300
      imageHeight: 300
      imageTitle: Two IT professionals brainstorming over paper
      buttons:
        - name: Blog
          url: blog
        - name: Contact me
          url: contact

taxonomies:
  category: categories
  series: series
  tag: tags
  topic: topics

###############################################################################
# Privacy settings
# https://gohugo.io/about/hugo-and-gdpr/
###############################################################################

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true


###############################################################################
# Security settings
# https://gohugo.io/about/security-model/
###############################################################################

security:
  enableInlineShortcodes: false
  exec:
    allow:
    - ^asciidoctor$
    - ^dart-sass-embedded$
    - ^go$
    - ^npx$
    - ^postcss$
