= Personal Website

:source-language: shell

:url_asciidoc: https://en.wikipedia.org/wiki/AsciiDoc[AsciiDoc]
:url_asciidoctor: https://asciidoctor.org[Asciidoctor]
:url_github: https://github.com
:url_github_actions: {url_github}/features/actions[GitHub Actions]
:url_github_pages: https://pages.github.com[GitHub Pages]
:url_hugo: https://gohugo.io[Hugo]
:url_repo: {url_github}/andreaslongo/personal-website
:url_site: https://www.andreaslongo.com[andreaslongo.com]
:url_static_site_generator: https://jamstack.org/generators[static site generator]
:url_workflow_deployment: {url_repo}/actions?query=workflow%3ADeployment
:url_workflow_deployment_batch: {url_repo}/workflows/Deployment/badge.svg


[link={url_workflow_deployment}]
image::{url_workflow_deployment_batch}[Deployment]

This repository contains the source code of my website {url_site}.

The site is built with {url_hugo}, a {url_static_site_generator}, and hosted on {url_github_pages}.

== Requirements

{url_hugo} must be installed alongside {url_asciidoctor} to build the site.

== Editing

I write content in the {url_asciidoc} format.

For a live preview of the website, clone the repository and launch a local Hugo server:

[source]
----
$ git clone --recurse-submodules https://github.com/andreaslongo/personal-website.git
$ cd ./personal-website
$ hugo server
----

The `hugo server` command builds the site and serves it via Hugo's built-in web server.
If you change a file, Hugo will automatically rebuild the site and refresh your web browser.

Useful options:

- `--buildDrafts` to include content marked as draft
- `--buildFuture` to include content with publishing date in the future
- `--debug` for debug output
- `--verbose` for verbose output

== Deployment

The site is deployed to {url_github_pages} when a new tag is pushed to the repository.
{url_github_actions} is used to automate the process.
