---
title: Text editor plugins for web APIs
date: 2021-02-11

series:
- Things I learned

categories:
- Software Development

topics:
- Web

tags:
- Hypertext Transfer Protocol (HTTP)
- Postman
- REST API
- RESTful API
- Representational state transfer (REST)
- Vim
- Visual Studio Code (vscode)
- Web
- Web API
- curl
---

:source-language: plaintext

:url_curl: https://curl.se/[curl]
:url_postman: https://www.postman.com/[Postman]
:url_postman_client: https://www.postman.com/product/api-client/
:url_vim: https://www.vim.org/[Vim]
:url_vim_rest_plugin: https://github.com/diepm/vim-rest-console
:url_vscode: https://code.visualstudio.com/[Visual Studio Code]
:url_vscode_rest_plugin: https://marketplace.visualstudio.com/items?itemName=humao.rest-client


Whether you are a developer or a consumer of RESTful web services, these two plugins might come in handy.

Send requests and receive responses to and from your REST APIs with your editor.
You can quickly explore your REST API without switching context to other tools like {url_curl} or {url_postman}.

- {url_vim_rest_plugin}[This plugin] is for {url_vim}.
It is a wrapper around `curl`.
- {url_vscode_rest_plugin}[This plugin] is for {url_vscode}. It is similar to the Vim plugin.


== Clean and Easy Requests

With both plugins, you write your API request as a text block in your editor and sent it to your API on demand.

The response shows up in a new editor buffer/window.

You can write multiple request blocks in the same file and send them separately.

Save your file for later reference, or share it with other developers as an example with your code.

One thing to note is that the syntax for the two plugins is slightly different.
You can't use a Vim request block directly with VS Code.
However, it is straightforward to adjust the request block to make it work.

*To send requests*

. Type in a request block.
. Place the cursor anywhere within the block.
. Hit the trigger key to send the request (default: `CTRL-J`).

.Vim `./example.rest`
[source, sh]
----
# vim: set filetype=rest

# global curl options
--silent
--include
--

# GET request

https://reqres.in
GET /api/users/2

# POST request

https://reqres.in
POST /api/users
{
    "name": "andreas",
    "job": "consultant"
}

# DELETE request

https://reqres.in
DELETE /api/users/2
----

== Tip

You can add query parameters like so.

----
https://reqres.in
GET /api/users?per_page=2&page=4
----

For better readability, you can write this instead.

----
https://reqres.in
GET /api/users
per_page=2
page=4
----

If your query parameters are more complex, you may have to enable https://github.com/diepm/vim-rest-console#54-line-by-line-request-body[Line-by-line Request Body] in Vim `:let b:vrc_split_request_body = 1`.

----
https://localhost:8001
GET /api/content/search
limit=10
cql=(type=page and space=IT and label=infrastructure)
----
