---
title: Active Directory - Managed Service Accounts
date: 2021-02-22

series:
- Things I learned

categories:
- IT Operations

topics:
- Microsoft Windows

tags:
- Active Directory (AD)
- Managed Service Account (MSA)
- PowerShell
---

:source-language: powershell

:url_rsat: https://docs.microsoft.com/en-US/troubleshoot/windows-server/system-management-components/remote-server-administration-tools[Remote Server Administration Tools (RSAT) for Windows]
:url_activedirectory: https://docs.microsoft.com/en-us/powershell/module/addsadministration[ActiveDirectory]
:url_new_adserviceaccount: https://docs.microsoft.com/en-us/powershell/module/addsadministration/new-adserviceaccount[New-ADServiceAccount]
:url_add_adcomputerserviceaccount: https://docs.microsoft.com/en-us/powershell/module/addsadministration/add-adcomputerserviceaccount[Add-ADComputerServiceAccount]
:url_install_adserviceaccount: https://docs.microsoft.com/en-us/powershell/module/addsadministration/install-adserviceaccount[Install-ADServiceAccount]
:url_test_adserviceaccount: https://docs.microsoft.com/en-us/powershell/module/activedirectory/test-adserviceaccount[Test-ADServiceAccount]
:url_uninstall_adserviceaccount: https://docs.microsoft.com/en-us/powershell/module/addsadministration/uninstall-adserviceaccount[Uninstall-ADServiceAccount]
:url_reset_adserviceaccountpassword: https://docs.microsoft.com/en-us/powershell/module/addsadministration/reset-adserviceaccountpassword[Reset-ADServiceAccountPassword]
:url_get_adserviceaccount: https://docs.microsoft.com/en-us/powershell/module/addsadministration/get-adserviceaccount[Get-ADServiceAccount]
:url_ntrights : https://ss64.com/nt/ntrights.html[NTRIGHTS.exe (Windows Server 2003 Resource Kit Tools)]


Traditionally, system administrators use Active Directory (AD) basic user accounts with limited permissions to run a service (Service Account).

*Managed Service Accounts (MSA)* are special accounts to eliminate the need for administrators to manually manage the credentials, passwords, and SPNs of traditional service accounts.
Also, with MSAs these tasks no longer disrupt a service (no downtime).

.Pro

Administration:: Automatic password changes. No manual password management.
Availability:: No service downtime for password changes.
Security:: Frequent password changes. User login to systems via MSA is not possible.

.Con

Initial Setup:: Initial setup and troubleshooting is more complex for MSAs than with basic user accounts.


== Types of managed service accounts

There are three types of managed service accounts.

Virtual Account:: Local system account *for local services*. Access to network resources is only possible via computer identity.
Managed Service Account (MSA):: Active Directory account *for generic services*.
Group Managed Service Account (gMSA):: Active Directory account *for cluster services*.


== Requirements

Use the PowerShell to work with managed service accounts.
Install and import the following module on the system on which you want to use MSAs.

----
$ Install-WindowsFeature RSAT-AD-PowerShell
$ Import-Module ActiveDirectory
----

Docs: {url_rsat}, {url_activedirectory}


== Create a managed service account in Active Directory

----
$ New-ADServiceAccount <account name> -RestrictToSingleComputer
----

Docs: {url_new_adserviceaccount}

// $ Add-ADComputerServiceAccount


== Install a managed service account on a system

Before you can use an MSA, you have to install it on the target system.

----
$ Install-ADServiceAccount <account name>
----

You can test the MSA from the system.

----
$ Test-ADServiceAccount <account name>

True
----

Now, use the Services console `Services.msc` to configure a service to use the MSA.

- Leave the password blank.
- Ensure that the account name ends with a dollar sign `$`.
- Start or restart the service.

Docs: {url_install_adserviceaccount}, {url_test_adserviceaccount}


== Remove a managed service account

You should remove an MSA from the system if it is no longer needed.

----
$ Uninstall-ADServiceAccount <account name>
----

Docs: {url_uninstall_adserviceaccount}


== Reset the password for a managed service account

Active Directory manages MSA passwords automatically.
You don't have to do anything.
Should you still have to reset the password manually, you can do so.

----
$ Reset-ADServiceAccountPassword <account name>
----

Docs: {url_reset_adserviceaccountpassword}


== Troubleshooting

////
=== Access Denied error while installing a managed service account

----
$ Install-ADServiceAccount -Identity msa-sql01
Install-ADServiceAccount : Cannot install service account. Error Message: '{Access Denied}
A process has requested access to an object, but has not been granted those access rights.'.
At line:1 char:1
+ Install-ADServiceAccount -Identity msa-sql01
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (msa-sql01:String) [Install-ADServiceAccount], ADException
    + FullyQualifiedErrorId : InstallADServiceAccount:PerformOperation:InstallServiceAcccountFailure,Microsoft.ActiveDirectory.Management.Commands.InstallADServiceAccount
----

----
Get-ADServiceAccount msa-sql01 -Properties PrincipalsAllowedToRetrieveManagedPassword
----
////

=== A service does not start with a managed service account

.Confirm that the MSA exists and is enabled in Active Directory.
----
$ Get-ADServiceAccount <account name>

DistinguishedName : CN=msa-sql01,CN=Managed Service Accounts,DC=example,DC=com
Enabled           : True
Name              : msa-sql01
ObjectClass       : msDS-ManagedServiceAccount
ObjectGUID        : 12345a13-12e3-1c23-b456-a123e123fd78
SamAccountName    : msa-sql01$
SID               : S-1-5-21-1234567890-1234567890-098765432-184195
UserPrincipalName :
----

.Confirm that the account name ends with a dollar sign `$`.

.Confirm that the account is installed on the system
----
$ Install-ADServiceAccount <account name>
----

.Confirm that the account has the `SeServiceLogonRight` permission
----
$ NTRights +r SeServiceLogonRight –u <account name>
----

Docs: {url_get_adserviceaccount}, {url_install_adserviceaccount}, {url_ntrights}
