---
title: A `sudo` like command for Cygwin
date: 2021-02-24

series:
- Things I learned

categories:
- IT Operations

topics:
- Microsoft Windows

tags:
- Bash
- Command-line interface (CLI)
- Command-line interpreter (CLI)
- Cygwin
- Linux
- Shell
- Unix
- Windows
- Zsh
- sudo
---

:source-language: shell

:url_cygwin: https://cygwin.com
:url_sudo: https://www.sudo.ws
:url_zsh: https://www.zsh.org


You can run commands from {url_cygwin}[Cygwin] with elevated permissions.

On Windows, you have something like `Run as different user` or `Run as administrator`.
And on Linux, you probably use the {url_sudo}[`sudo`] command for this.

To get similar functionality on Cygwin, you can add a new alias to your shell's config file.
The following is for {url_zsh}[Zsh], but it should also work for other bash-like shells.

.`~/.zshrc`
----
alias sudo='cygstart --action=runas'
----

Now you can run something like this to test the alias.

----
$ sudo touch sudo-test
----

Windows will ask for your username and password.
Then it will run the command in the context of the given user.

That works, but the user experience is not great.

Your command gets executed in a new Cygwin process which automatically exits when the command returns.
Also, the user prompt is GUI based which interrupts your CLI workflow.
